more test infrastructure improvements

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -3,18 +3,12 @@ BUNDLE := ../bin/bundle
 REF := references
 
 IS_GIT_TREE := (which git && git ls-files --error-unmatch) >/dev/null 2>&1
-IS_GIT_TREE := false
-
-EXP_OK := || true
-EXP_FAIL := || true
+CONTINUE := true
 ifeq (no,$(shell $(IS_GIT_TREE) || echo no))
-  EXP_OK := || exit 1
-  EXP_FAIL := && exit 1 || true
+  CONTINUE := exit 1
 endif
 
 HR=echo "========================================================="
-STARTING_STEP = @echo "STARTING STEP $@"
-
 T = @function testcase {\
         local name=$$1; shift; \
         local retExp=$$1; shift; \
@@ -23,23 +17,45 @@ T = @function testcase {\
 	( \
           set -x; \
           $$@ >references/$$name.res 2>&1 || ret=$$?; \
-	  test $$ret = $$retExp $(EXP_OK); \
-          diff -u references/$$name.res references/$$name.ref $(EXP_OK); \
-          diff -u -r repo references/$$name $(EXP_OK); \
-	); \
-	echo "SUCCESSFULLY FINISHED TEST $$name"; echo ""; $(HR); \
+	  test $$ret = $$retExp || exit 1; \
+          diff -u references/$$name.res references/$$name.ref || exit 1; \
+          diff -u -r repo/bundle/*/*/conf references/$$name/bundle/*/*/conf || exit 1; \
+        ) && echo "TEST OK: $$name" || { echo "TEST FAILED: $$name"; $(CONTINUE); }; \
+        echo ""; $(HR); \
     }; testcase
 
 
-main: clitests
+main: bundle_tests git_diff_results
 
-clitests: clean _clitest_init 
-
-_clitest_init:
-	$(T) clitest_init 0 $(BUNDLE) init bionic --no-clean-commit
+bundle_tests: clean 
+	$(T) bundle_init 0 $(BUNDLE) init bionic --no-clean-commit
+	$(T) bundle_apply1 0 $(BUNDLE) apply bionic/0001
 
 clean:
 	rm -Rf repo
 	rm -f $(REF)/*.res
 	@$(HR)
+
+
+ifeq (yes,$(shell $(IS_GIT_TREE) && echo yes))
+  returncodes:
+	make main IS_GIT_TREE=false
+else
+  returncodes:
+	@echo "Skipping returncodes as this is not a git tree"
+endif
+
+
+ifeq (yes,$(shell $(IS_GIT_TREE) && echo yes))
+  git_diff_results:
+	@echo "Using git diff to compare results and references"
+	bash -c 'for i in references/*.res; do \
+		cp $$i $${i/.res/.ref}; \
+	done'
+	git diff --quiet --exit-code references/*.ref
+	@echo "FINISHED SUCCESSFULLY"
+else
+  git_diff_results:
+	@echo "Skipping git_diff_results as this is not a git tree"
+endif
 
